version: '3.4'
services:
  kafka:
    container_name: kafka
    build: 
      context: .
      args: 
        password: ${PASSW}
        kafka_version: ${KAFKA_VERSION}
        kafka: ${KAFKA}
      cache_from:
        - ${SUPERVISORD_IMAGE}
    depends_on:
      - zookeeper
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 2G
        reservations: 
          cpus: '0.15'
          memory: 1G
    extra_hosts:
      - ${ZOOKEEPER_ETC_HOSTS}
      - ${KAFKA_ETC_HOSTS}
    networks:
      app_net:
        ipv4_address: ${KAFKA_IP}
  zookeeper:
    container_name: kafka_zookeeper
    build:
      context: ../commons/zookeeper
      args:
        password: ${PASSW}
        zookeeper_version: ${ZOOKEEPER_VERSION}
      cache_from:
        - ${SUPERVISORD_IMAGE}
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: 3G
        reservations: 
          cpus: '0.15'
          memory: 1G
    extra_hosts:
      - ${ZOOKEEPER_ETC_HOSTS}
      - ${KAFKA_ETC_HOSTS}
    networks:
      app_net:
        ipv4_address: ${ZOOKEEPER_IP}
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/29